In [0]:
#question1
pip install geopy

In [0]:
from geopy.geocoders import Nominatim
city = ["Vijaynagar","Mumbai","Palasia","Indore"]
# city = Palasia
geolocator = Nominatim()
for i in range(len(city)):
  location = geolocator.geocode(city[i])
  print((location.latitude, location.longitude))


/usr/local/lib/python3.6/dist-packages/geopy/geocoders/osm.py:143: UserWarning: Using Nominatim with the default "geopy/1.17.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  UserWarning


(27.4600791, 96.6184625)
(18.9387711, 72.8353355)
(22.7291382, 75.8888823)
(22.7203851, 75.8682103)


In [0]:
#question2

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
 





In [0]:
df = pd.read_csv('/rubin_linear.csv')

df.head()


29204.45 0.00    0.00    2352.98 1661.54 1293.29 1423.05 864.53  1138.91 1183.72 1298.06 3297.26 2638.59 1092.86 923.44  803.40  808.72  1062.89 832.35 
0  29204.46 0.00    0.00    2347.76 1662.21 1288....                                                                                                      
1  29204.47 0.00    0.00    2358.69 1642.10 1284....                                                                                                      
2  29204.48 0.00    0.00    2347.02 1654.68 1288....                                                                                                      
3  29204.49 0.00    0.00    2344.54 1651.15 1286....                                                                                                      
4  29204.50 0.00    0.00    2348.76 1656.45 1281....

In [0]:
X = df.iloc[:, :-1].values
Y = df.iloc[:, 1].values


In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [0]:
df= pd.read_csv('rubin1.txt',delimiter=r'\s+',encoding='utf-8')
# df= df.iloc[2880000:2920000,1:]
X= df.iloc[: ,2: ]
Y= df.iloc[: ,1:2]
from sklearn import linear_model, model_selection
model= linear_model.LinearRegression()
df.head()

Time  ...  s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16
28804.46 0.0 0.0 2345.03 1668.19 1506.70 1671.29 971.62 1246.16  1332.45  ...                                             925.77  
28804.47 0.0 0.0 2341.07 1659.99 1492.92 1689.05 990.27 1243.07  1320.96  ...                                             926.75  
28804.48 0.0 0.0 2334.62 1641.21 1497.01 1669.96 981.43 1252.54  1327.85  ...                                             913.16  
28804.49 0.0 0.0 2347.76 1665.97 1487.55 1663.09 986.53 1243.27  1317.21  ...                                             929.08  
28804.50 0.0 0.0 2347.52 1662.21 1495.29 1660.44 980.06 1250.48  1330.98  ...                                             918.98  

[5 rows x 10 columns]

In [0]:
from sklearn import linear_model, model_selection
model= linear_model.LinearRegression()
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X,Y,test_size=0.25)
model.fit(X_train,Y_train)

model.score(X_train,Y_train)
model.score(X_test,Y_test)

0.9997428149524703

In [0]:
pred= model.predict(X_test)

In [0]:
from sklearn.metrics import mean_squared_error
test_set_rmse= (np.sqrt(mean_squared_error(Y_test, pred)))

In [0]:
print(test_set_rmse)

18.765229679330435


In [0]:
pip install sys

  ERROR: Could not find a version that satisfies the requirement sys (from versions: none)
ERROR: No matching distribution found for sys


In [0]:
#k fold testing
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
for train, test in kf.split(X_train):
  print("%s %s" % (train, test))

[10000 10001 10002 ... 29996 29997 29998] [   0    1    2 ... 9997 9998 9999]
[    0     1     2 ... 29996 29997 29998] [10000 10001 10002 ... 19997 19998 19999]
[    0     1     2 ... 19997 19998 19999] [20000 20001 20002 ... 29996 29997 29998]


In [0]:
#question 3
pip install idx2numpy

In [0]:
import idx2numpy
import numpy as np
file = 'train-images.idx3-ubyte'
arr = idx2numpy.convert_from_file(file)
labl = 'train-labels.idx1-ubyte'
lbarr = idx2numpy.convert_from_file(labl)
my_data = []
my_lables = []

for i in range(len(lbarr)):
    if(lbarr[i]==2 or lbarr[i]==3):
        my_lables.append(lbarr[i])
        my_data.append(arr[i])

my_lables = np.asarray(my_lables)
my_data = np.asarray(my_data)

avg = []
for data in my_data:
    avg.append(np.mean(data))
avg = np.asarray(avg)

cor = []
for data in my_data:
    cor.append(np.corrcoef([data[:,:14].flatten(), np.flip(data[:,14:],axis=1).flatten()])[0][1])
cor = np.asarray(cor)

a1 = []
s1 = []
a2 = []
s2 = []
for i in range(len(my_lables)):
    if my_lables[i]==1:
        a1.append(avg[i])
        s1.append(cor[i])
    elif my_lables[i]==2:
        a2.append(avg[i])
        s2.append(cor[i])

import matplotlib.pyplot as plt

plt.figure(figsize=(20,10))
plt.xlabel('Avg')
plt.ylabel('Sym')
d1 = plt.scatter(a1,s1,color='blue')
d2 = plt.scatter(a2,s2,color='red')
plt.legend((d1, d2), ('Digit 1', 'Digit 2'), scatterpoints=1, loc='lower left', ncol=3, fontsize=8)

In [0]:
for i in range(len(cor)):
    if np.isnan(cor[i]):
        cor[i] = 0

ls=[]
for i in range(len(cor)):
    ls.append((avg[i],cor[i]))
    
from sklearn.cluster import KMeans
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', max_iter=300, n_init=10, random_state=0)
    kmeans.fit(ls)
    wcss.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss)
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

In [0]:
kmeans = KMeans(n_clusters=4, init='k-means++', max_iter=300, n_init=10, random_state=0)
pred_y = kmeans.fit_predict(ls)
plt.figure(figsize=(20,10))
plt.xlabel('Avg')
plt.ylabel('Sym')
plt.title('For 4 Clusters')
plt.scatter(avg, cor)
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s=300, c='red')
plt.show()

In [0]:
kmeans = KMeans(n_clusters=2, init='k-means++', max_iter=300, n_init=10, random_state=0)
pred_y = kmeans.fit_predict(ls)
plt.figure(figsize=(20,10))
plt.xlabel('Avg')
plt.ylabel('Sym')
plt.title('For 2 Clusters')
plt.scatter(avg, cor)
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s=300, c='red')
plt.show()